#FROM drupal:8-fpm
#FROM 
##
nginx:
    image: nginx
    hostname: nginx.localhost
    restart: always
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
    # volumes_from:
    #     - storage-drupal
    links:
        - "docker-manager"
        - "api-staging"
    ports:
        - "80:80"
#####docker-manager!!
docker-manager:
    image: portainer/portainer
    hostname: docker-manager
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    # ports:
    #     - "9000"

api-staging:
    image: drupal
    hostname: api-staging
    restart: always
    # volumes_from:
    #     - storage-drupal
    links:
        - "db-mariadb"
    # ports:
    #     - "8080:80"

#################
db-mariadb:
    image: mariadb
    hostname: mariadb-localhost
    restart: always
    # volumes_from:
    #     - storage-mysql
    environment:
        - MYSQL_USER=drupal
        - MYSQL_PASSWORD=drupal
        - MYSQL_DATABASE=drupal
        - MYSQL_ROOT_PASSWORD=drupal